import "../styles/global.css";
import { NavBar } from './components/NavBar';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/hacker.png" />
        <title>Portfolio Alisser</title>
      </head>
      <body>
        <NavBar />
        {children}
      </body>
    </html>
  )
}
